# Generated by Django 3.0.5 on 2020-04-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='file',
        ),
        migrations.AddField(
            model_name='blog',
            name='docfile',
            field=models.FileField(default=None, upload_to='docs'),
        ),
    ]
