# Generated by Django 3.0.5 on 2020-04-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200419_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='docfile',
            field=models.FileField(upload_to=''),
        ),
    ]
